### ISSUE TITLE
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from sapsii;'

### ISSUE THREAD

**Issue by GordonDoo** [Erakhsha/ICU72hReadmissionMIMICIII#1]
In file generate_datasets when run File "main.py", line 131, in getfeaturesFromSeverityScoreConcepts
    sapsii = conn.executeQuery('''select * from sapsii;''') have a mistake,
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from sapsii;': wrong :  relation "sapsii" does not exist.
LINE 1: select * from sapsii;

**Comment by Nathan-C-Hurley** [comment]
In order to create sapsii and other severity scores, please see the severity score scripts available here: https://github.com/MIT-LCP/mimic-code/tree/master/concepts/severityscores
